#!/usr/bin/env Rscript
args = commandArgs(trailingOnly=TRUE)

########################
########################
##
##
## This R script requires: 
##  1. the bootstrapped genomic windows file chromosome,startCoord,EndCoord,NbSitesSurveyed,NbSampledWindow
##  2. the SFS folder with the 2D and the multi-SFS inside as generated by boot_fromGTmatrixToSfs_IV.sh
##
##  This script is called using: computingOBS_2D_multi_SFS.7.R <inDir> <outDir> <strains/clade> <GTm> <model> <samples>
##
##  Isabel Alves - June 2025
##
########################
########################

#library(tidyverse, lib.loc = "/shared/home/ialves/R/x86_64-redhat-linux-gnu-library/4.3")
library(tidyverse)
#library(ggpubr)
#library(ggplot2)
set.seed(988599694)

# arguments 
inDir <- args[1]
modelDir <- args[2]
modelLabel <- args[3]
boot <- args[4]

# To debug
# inDir <- "/shared/home/ialves/demoHist_yeast3039/04-analysis/fastsimcoal/SFS_134samples"
# modelDir <- "/shared/home/ialves/demoHist_yeast3039/04-analysis/fastsimcoal/fiveClades"
# modelLabel <- "TwoDomest_EurOld_Taiw_stru"
# boot <- 1

# ----------------
# opening files
# ----------------
bootWindows <- read.table(paste0(inDir, "/bootstrap_DS_", boot, "/allsites.25samples.noORF.noMiss.500.siteden.boot",boot, ".fullDS" ), header = F, sep = " ")
multiSFS <- scan(paste0(modelDir, "/", modelLabel,  "_", boot, "_dSFS/", modelLabel,  "_", boot,"_DSFS.tmp"), nlines = 1, what = numeric(), skip = 2)
headerOne <- paste(scan(paste0(modelDir, "/", modelLabel,  "_", boot, "_dSFS/", modelLabel,  "_", boot,"_DSFS.tmp"), nlines = 1, what = character()), collapse=" ")
headerTwo <- paste(scan(paste0(modelDir, "/", modelLabel,  "_", boot, "_dSFS/", modelLabel,  "_", boot,"_DSFS.tmp"), nlines = 1, what = character(), skip = 1), collapse="\t")
# ----------------
# computing the nb of surveyed sites 
# ----------------
nbSurveyedSites <- sum(bootWindows[,4]*bootWindows[,5])

# ----------------
# getting the nb of mono from the DSFS.tmp file
# ----------------
monoTmp <- multiSFS[1]
multiSFS[1] <- 0

# ----------------
# getting the nb of variable sites
# ----------------
variableSites <- sum(multiSFS)
nbMonomorphic <- nbSurveyedSites-variableSites
multiSFS[1] <- nbMonomorphic

# ----------------
# printing 
# ----------------
cat(headerOne, file=paste0(modelDir, "/", modelLabel,  "_", boot, "_dSFS/", modelLabel,  "_", boot,"_DSFS.obs"), sep = "\n")
cat(headerTwo, file=paste0(modelDir, "/", modelLabel,  "_", boot, "_dSFS/", modelLabel,  "_", boot,"_DSFS.obs"), sep = "\n", append = T)
cat(paste(multiSFS, collapse = "\t"), file=paste0(modelDir, "/", modelLabel,  "_", boot, "_dSFS/", modelLabel,  "_", boot,"_DSFS.obs"), sep = "\n", append = T)

# --------------------------
# ----------------
# ------

